// This file was autogenerated by calcdeps.py
goog.addDependency("../../../pl/src/debugDiv.js", ['pl.DebugDiv'], ['goog.asserts', 'goog.debug.LogManager', 'goog.dom', 'goog.style']);
goog.addDependency("../../../pl/src/ex.js", ['pl.ex'], ['goog.style', 'goog.string', 'goog.array', 'goog.math.Size']);
goog.addDependency("../../../pl/src/fpsLogger.js", ['pl.FpsLogger'], []);
goog.addDependency("../../../pl/src/gfx.js", ['pl.gfx'], ['goog.math.Size']);
goog.addDependency("../../../pl/src/keyBinding.js", ['pl.KeyBinding', 'pl.KeyBindingEvent'], ['goog.events.Event', 'goog.events.EventTarget', 'goog.ui.KeyboardShortcutHandler', 'goog.ui.KeyboardShortcutHandler.EventType']);
goog.addDependency("../../../pl/src/preload.js", ['pl.Preload'], ['goog.object']);
goog.addDependency("../../../pl/src/stats.js", ['pl.Stats'], ['goog.dom']);
goog.addDependency("../../../pl/src/retained/container.js", ['pl.retained.Container'], ['goog.array', 'pl.retained.Element']);
goog.addDependency("../../../pl/src/retained/element.js", ['pl.retained.Element'], ['goog.color.alpha', 'goog.math.Coordinate', 'goog.math.Rect', 'goog.math.Size', 'goog.graphics.AffineTransform', 'pl.gfx']);
goog.addDependency("../../../pl/src/retained/stage.js", ['pl.retained.Stage'], ['goog.math.Coordinate', 'goog.math.Size', 'pl.retained.Element', 'pl.ex']);
goog.addDependency("../../../pl/src/retained/text.js", ['pl.retained.Text'], ['pl.gfx', 'pl.retained.Element']);
goog.addDependency("../../../pl/src/retained/tileLayer.js", ['pl.retained.TileLayer'], ['goog.math.Vec2', 'goog.asserts', 'pl.ex']);
